### ISSUE TITLE
[Feature Request] Upload screenshot to QA Touch

### ISSUE THREAD

**Issue by andisan86** [kanidjar/cypress-qatouch-reporter#4]
Hi,

Thank you for this plugin. I would like to request a feature to upload screenshot to QA Touch test result.

Kind regards,

**Comment by kanidjar** [comment]
Hello @andisan86, I will try to have a look at it as soon as I can. I keep you updated.

**Comment by kanidjar** [comment]
hello @andisan86, in order to push the screenshot to QATouch, I need to use another endpoint that is currently returning a 500 error. I'm in touch with QATouch to fix the issue on their side.

**Comment by kanidjar** [comment]
@andisan86 : feature merged :) Every time a test fails, a screenshot is uploaded to QATouch (see the results history tab of your test run). Please have a look at the documentation.
